name: Docker Image CI for GHCR
 
on:
    push
 
jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: npm install
              run: npm ci
            - name: run the unit tests
              run: npm test
 
            - name: Build and push the image
              run: |
                docker login --username adityapadgal --password ${{secrets.ACCESS_CIPHER}} ghcr.io
                docker build -t ghcr.io/adityapadgal/arithmetic-service:latest --file Dockerfile .  
                docker push ghcr.io/adityapadgal/arithmetic-service:latest

            - name: Publish the image to azure container registry
              run: |
                docker login --username practicum15 --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum15ad.azurecr.io
                docker tag ghcr.io/adityapadgal/arithmetic-service:1   practicum15ad.azurecr.io/arithmetic-service:1
                docker push practicum15ad.azurecr.io/arithmetic-service:1